name = "aiocatalogs"
main = "./packages/platforms/cloudflare/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

# Observability
[observability]
enabled = true
head_sampling_rate = 1 

# ------------------------------
# --- Production environment ---
# ------------------------------

[vars]
AIOCATALOGS_TRUSTED_ORIGINS = "https://aio.pantelx.com, https://aiocatalogs.jqrw92fchz.workers.dev"
AIOCATALOGS_API_RATE_LIMIT = true
AIOCATALOGS_API_MAX_REQUESTS = 50
AIOCATALOGS_API_MAX_ITEMS_MDBLIST = 1000

LOG_LEVEL = "info"
LOG_ENABLE_TIMESTAMPS = true
LOG_TIMESTAMP_FORMAT = "dd.MM.yyyy HH:mm:ss"
LOG_TIMEZONE = "Europe/Berlin"

[[d1_databases]]
binding = "DB"
database_name = "aiocatalogs"
database_id = "817cf993-5aa5-4d1d-bab0-bbb61539631d"
migrations_dir = "./packages/platforms/cloudflare/migrations"

# -------------------------------
# --- Development environment ---
# -------------------------------

[env.dev.vars]
AIOCATALOGS_TRUSTED_ORIGINS = "http://localhost:8787"
AIOCATALOGS_API_RATE_LIMIT = false
AIOCATALOGS_API_MAX_REQUESTS = 5
AIOCATALOGS_API_MAX_ITEMS_MDBLIST = 1000

LOG_LEVEL = "debug"
LOG_ENABLE_TIMESTAMPS = true
LOG_TIMESTAMP_FORMAT = "dd.MM.yyyy HH:mm:ss"
LOG_TIMEZONE = "Europe/Berlin"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "aiocatalogs"
database_id = "817cf993-5aa5-4d1d-bab0-bbb61539631d"
migrations_dir = "./packages/platforms/cloudflare/migrations"

[dev]
port = 8787
